version: '3'
services:
  emu:
    build: .
    image: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
    ports:
      - "{{ cookiecutter.http_port }}:{{ cookiecutter.http_port }}"


# docker-compose build
# docker-compose up
# docker-compose down
# docker-compose rm
