# conda env create -f environment-docs.yml
name: {{ cookiecutter.project_slug }}-docs
channels:
- conda-forge
- defaults
dependencies:
- python >=3.9,<3.13
- pywps >=4.5.1,<4.6
- sphinx >=7.0.0
- nbsphinx
- ipython
