name: cookiecutter-birdhouse
channels:
- defaults
- conda-forge
dependencies:
- pip
- cryptography
- pyyaml
- cookiecutter
- pytest
- pytest-cookies
- bump2version
- watchdog
- pip:
  # https://timothycrosley.github.io/cruft/
  - cruft
  # https://scaraplate.readthedocs.io
  - git+https://github.com/tlvu/scaraplate@4602a26c31a614052906ec3d78fda45b2765b156
