name: cookiecutter-birdhouse
channels:
- defaults
- conda-forge
dependencies:
- pip
- cryptography
- pyyaml
- cookiecutter
- pytest
- pytest-cookies
- pytest-notebook
- bump2version
- watchdog
- ipython
- nbsphinx
- nbval
- nbconvert
