name: cookiecutter-birdhouse
channels:
  - conda-forge
dependencies:
  - python>=3.7,<3.10
  - alabaster
  - bump2version
  - cookiecutter >=2.1.0
  - cruft
  - cryptography
  - pip
  - psutil
  - pytest >=6.2.4
  - pytest-cookies
  - pywps
  - pyyaml
  - sphinx >=5.3.0
  - watchdog
