name: cookiecutter-birdhouse
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.14
  - alabaster >=1.0.0
  - python-build >=1.2.2
  - bump-my-version >=0.30.1
  - cookiecutter >=2.6.0
  - cruft >=2.15.0
  - cryptography
  - pip >=25.0
  - pre-commit >=4.0.0
  - psutil >=6.0.0
  - pytest >=8.0.0
  - pytest-cookies >=0.7.0
  - pywps >=4.6
  - pyyaml >=6.0.2
  - ruff >=0.9.0
  - sphinx >=7.1.0
  - tox >=4.24.1
  - watchdog >=4.0.0
