name: cookiecutter-birdhouse
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - bump2version
  - cookiecutter
  - cruft
  - cryptography
  - pip
  - pytest
  - pytest-cookies
  - pyyaml
  - watchdog
