name: {{ cookiecutter.project_slug }}
channels:
- conda-forge
- defaults
dependencies:
- pip
- python>=3.6,<3.8
- pywps>=4.2.4,<4.3
- jinja2
- click
- psutil
# tests
- pytest
- pytest-notebook
- bump2version
- ipython
- nbsphinx
- nbval
- nbconvert
#- pip:
#  - -e git+https://github.com/geopython/pywps@master#egg=pywps
