# GitHub CI build pipeline
name: Cookiecutter PyPackage CI build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install coverage
          if  [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; else pip install .; fi
      - name: Run Tests
        run: |
          python -m pytest tests
      - name: Run package creation
        run: |
          python -m pip install --user --upgrade build
          python -m build --sdist
      - name: Archive package
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: cookie-cutter
          path: src/dist
